# .readthedocs.yaml
# Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - plantuml
  tools:
    python: "3.10"
  jobs:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --no-root --only docs

sphinx:
  configuration: docs/src/conf.py
